### ISSUE TITLE
Max number of rows

### ISSUE THREAD

**Issue by olisgail** [ExLibrisGroup/ExlTableauWDC#9]
We are in the early stages of exploring using Tableau. We have successfully used the Web Data Connector for Alma Analytics.
One thing I'm noticing is that the maximum "Max number of rows" is 50,000.
Is there any way around that maximum? I am from SUNY and we were hoping to use Tableau for Network Zone Analytics, which will quite often include reports with more than 50k rows.

Thanks!

Gail Pawlowski
SUNY - State University of New York

**Comment by jweisman** [comment]
Hi @olisgail . Glad the web data connector has been helpful. Our main concern is the responsiveness of the Tableau interface with so much data. Have you used the connector with large reports? If so, how has your experience been? How many rows do you expect to want to use in reports accessed from Tableau?

**Comment by olisgail** [comment]
Hi @jweisman,
Thanks for the quick reply>
We don't have any specific reports yet. But you are correct about the responsiveness.

So far I have found that pulling data from the NZ, even with less than 50,000 rows, takes a long time to load or sometimes doesn't load at all. But when I test from a single institution IZ it runs and loads much faster. Is that to be expected? In your opinion, is the WDC made for a large consortium like SUNY (60 IZs)?

**Comment by jweisman** [comment]
Hi @olisgail . There's 2 aspects at play here:
1. The performance of the native report in Analytics
2. The retrieval of the report by the connector for display in Tableau

I would first check the report in Analytics and be sure that it performs well there. It will take longer in Tableau as it needs to retrieve all of the results for display there. We haven't had experience with the connector in large environments, so we're happy to receive your feedback from real-life usage.

Another alternative is to export data from a report in Analytics into CSV and then load it into Tableau. The limit for CSV files is currently 500,000 records.

**Comment by ctgraham** [comment]
We've done some benchmarking which may be of interest here.

Web Data Connector as-is:

- 23K records (2 seconds execution in Analytics)
  - 12 seconds "executing query" in Tableau
  - 4 minutes to pull records via "Update Now" in Tableau
- 56K records (6 seconds execution in Analytics)
  - 12 seconds "executing query" in Tableau
  - 10 minutes to pull records via "Update Now" in Tableau
- 240K records (20 seconds execution in Analytics)
  - 34 seconds "executing query" in Tableau
  - 33 minutes to pull records via "Update Now" in Tableau

An excessive amount of time was spent paging the recordset at 25 records per API call, so I modified the WDC to page at 1000 records.  This provided substantial improvement:
- 56K records
  - 12 seconds "executing query" in Tableau
  - 2 minutes to pull records via "Update Now" in Tableau
- 70K records
  - 13 seconds "executing query" in Tableau
  - 2 minutes to pull records via "Update Now" in Tableau
- 240K records
  - 27 seconds "executing query" in Tableau
  - 4 minutes to pull records via "Update Now" in Tableau

As an aside, both of the 240K runs reported successful when debugging the WDC, but the rows did not display in Tableau upon completion, which I believe to be a Tableau issue, which I'm following up on independently.

I will attach PRs to this Issue with proposed changes to increase the record limit and page size.

**Comment by jweisman** [comment]
Thanks for this! We'll take a look.

**Comment by jweisman** [comment]
Thanks @ctgraham for your work here. I merged the changes and updated the production connector at:
https://eu-st01.ext.exlibrisgroup.com/delivery/wdc/exl.html

Please give it a try and let us know how it goes.

**Comment by ctgraham** [comment]
Large reports also appear to be constrained by an internal limit within third party tooling used by Tableau, specifically (from Tableau Support):

> Prior to Tableau 2019.4, Web Data Connectors used an internal browser in Tableau called Qt WebKit. In Tableau 2019.4 and later, Web Data Connectors use Qt WebEngine, a Chromium-based browser. The Qt WebEngine is a significant upgrade over the previous internal browser and WDC developers will benefit from being able to use modern JavaScript tools and practices that improve the user interface and user interactions. The new browser provides better support for HTML5 and allows developers to use modern debugging tools and the Chrome DevTools for debugging WDC code. 
>
> However, because of the internal browser change, some customers are expected to experience problems using their existing connectors in Tableau 2019.4 and later. In Tableau 2019.4 and later, Web Data Connectors use Qt WebEngine as the internal browser. The version of the Qt WebEngine we currently use has a limitation in its data communication channel of approximately 128MB. This limitation restricts the amount of data that you can append to the extract at a time. In addition, the actual amount of data you can append could appear to be much smaller than 128MB, as there is often some additional information or metadata associated with the data. If your WDC appends more data that can be transmitted, the WDC is created and initialized but no data is added. For information on the Qt limitation, see https://bugreports.qt.io/browse/QTBUG-47629
>
> **Resolution:** Depending upon the size of your data, it’s a best practice to insert data into the table in amounts smaller than 128MB (accounting for the additional metadata). For more information and for example, code showing one way of breaking up the data into smaller chunks, see https://tableau.github.io/webdataconnector/docs/wdc_get_data.html.

The QTBUG report notes that there is no way to detect or catch a failure caused by this limit.

I'm going to guess that in large reports, the 128MB limit is exceeded by the `tableData` array:
https://github.com/ExLibrisGroup/ExlTableauWDC/blob/15c2b2f374e124d1caeaa7700eb03d1177d96830/exl.js#L140
If so, the fix would be to call `table.appendData()` more frequently, rather than deferring the call to only after all results had been fetched.
https://github.com/ExLibrisGroup/ExlTableauWDC/blob/15c2b2f374e124d1caeaa7700eb03d1177d96830/exl.js#L59-L61

**Comment by jweisman** [comment]
Thanks @ctgraham - instead of the approach you suggested in #12, I chunked the call to `appendRows` after all of the data is retrieved from analytics (01013f9). The connector has been updated in production. Can you let us know how that works for you?

**Comment by ctgraham** [comment]
@jweisman, I think there is a breaking typeo in the commit, but I also think the general strategy will fail.  Based on my reading of the ticket Tableau support pointed to, I think it is the size of the `tableData` array itself which is failing by exceeding ~128MB.  I'll confirm locally.

**Comment by ctgraham** [comment]
@jweisman, I've successfully tested the new `chunkData()` call, with the rename of `tableData` to `data`.  It appears that it is an internal to `table.appendRows()` which was hitting the QT limit, not the array itself.

**Comment by jweisman** [comment]
Thanks @ctgraham - I fixed the parameter name to `chunkData` (it still worked because `tableData` is defined as a global variable, hence my test in the [Tableau WDC Simulator](https://tableau.github.io/webdataconnector/Simulator/) worked). 

Glad to hear your tests were successful. Hopefully the WDC handles larger reports better now.

Thanks for your contribution!

**Comment by ctgraham** [comment]
@jweisman , just one more followup here.  The WDC still presents [a upper limit of 250K](https://github.com/ExLibrisGroup/ExlTableauWDC/blob/c118bdb7566416ac95aaf35fa170d1b09ab6aa76/exl.html#L89) in the production deployment.  Any reason not to also add an "Unlimited"?

**Comment by jweisman** [comment]
Hi @ctgraham - we were just concerned that Tableau wouldn't work well with so many rows coming back from the data connector. Do you have a use case you can test to see how it works with so much data and give us some feedback?

**Comment by ctgraham** [comment]
Hi, @jweisman .  One example that our Assessment folks have suggested is that of collection modelling.  One of our locations has in excess of 570K rows; staff are currently exporting the data in chunks (by LC prefix), and then cobbling it together in notepad (!) to then upload into Tableau.  Removing the limit on the WDC would substantially simplify this process.  Tableau itself certainly handles datasets much larger than this.  We have successfully tested the WDC with the example dataset of 570K rows by adding [an option with value of "-1" to `#selectMaxRows`](https://github.com/ExLibrisGroup/ExlTableauWDC/blob/c118bdb7566416ac95aaf35fa170d1b09ab6aa76/exl.html#L76-L90) (runtime 8 minutes at 1K paging).  [The code to respect that value](https://github.com/ExLibrisGroup/ExlTableauWDC/blob/c118bdb7566416ac95aaf35fa170d1b09ab6aa76/exl.js#L172) already exists in the javascript.

**Comment by jweisman** [comment]
Thanks for the info @ctgraham . We updated the possible max rows to 750000. Let us know how that works out for you.
